export const CONFIGS = {
  GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID!,
  GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY!,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_AUTH_URI: process.env.GOOGLE_AUTH_URI!,
  GOOGLE_TOKEN_URI: process.env.GOOGLE_TOKEN_URI!,
  GOOGLE_AUTH_PROVIDER_CERT_URL: process.env.GOOGLE_AUTH_PROVIDER_CERT_URL!,
  GOOGLE_CLIENT_CERT_URL: process.env.GOOGLE_CLIENT_CERT_URL!,
  GOOGLE_SHEET_ID: process.env.GOOGLE_SHEET_ID!,
  VERIFF_API_KEY: process.env.VERIFF_API_KEY!,
};
