name: Generate GOOGLE_SHEET_API_KEY.ts

on:
  push:
    branches:
      - main

jobs:
  create-secrets-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GOOGLE_SHEET_API_KEY.ts file
        run: |
          echo "export const GOOGLE_JSON_API_KEY = {" > ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  type: 'service_account'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  project_id: '${{ secrets.GOOGLE_PROJECT_ID }}'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  private_key_id: '5015576de146091e145d9f4ffc16468e6cbff235'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  private_key: '${{ secrets.GOOGLE_PRIVATE_KEY }}'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  client_email: '${{ secrets.GOOGLE_CLIENT_EMAIL }}'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  client_id: '${{ secrets.GOOGLE_CLIENT_ID }}'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  auth_uri: '${{ secrets.GOOGLE_AUTH_URI }}'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  token_uri: '${{ secrets.GOOGLE_TOKEN_URI }}'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  auth_provider_x509_cert_url: '${{ secrets.GOOGLE_AUTH_PROVIDER_CERT_URL }}'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  client_x509_cert_url: '${{ secrets.GOOGLE_CLIENT_CERT_URL }}'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  universe_domain: 'googleapis.com'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "  sheetId: '${{ secrets.GOOGLE_SHEET_ID }}'," >> ./src/GOOGLE_SHEET_API_KEY.ts
          echo "};" >> ./src/GOOGLE_SHEET_API_KEY.ts

      - name: Verify GOOGLE_SHEET_API_KEY.ts
        run: cat ./src/GOOGLE_SHEET_API_KEY.ts
